package com.adkun.seckill.dao;

import com.adkun.seckill.entity.Item;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Mar 07 21:18:33 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Mar 07 21:18:33 CST 2021
     */
    int insert(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Mar 07 21:18:33 CST 2021
     */
    Item selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Mar 07 21:18:33 CST 2021
     */
    List<Item> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Mar 07 21:18:33 CST 2021
     */
    int updateByPrimaryKey(Item record);

    /**
     * 增加销量
     *
     * @param id
     * @param amount
     * @return
     */
    int increaseSales(Integer id, Integer amount);

    /**
     * 查询正在秒杀的商品
     *
     * @return
     */
    List<Item> selectOnPromotion();
}