package com.adkun.mySeckill.dao;

import com.adkun.mySeckill.entity.SerialNumber;
import java.util.List;

public interface SerialNumberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serial_number
     *
     * @mbg.generated Sun Mar 07 22:26:42 CST 2021
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serial_number
     *
     * @mbg.generated Sun Mar 07 22:26:42 CST 2021
     */
    int insert(SerialNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serial_number
     *
     * @mbg.generated Sun Mar 07 22:26:42 CST 2021
     */
    SerialNumber selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serial_number
     *
     * @mbg.generated Sun Mar 07 22:26:42 CST 2021
     */
    List<SerialNumber> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serial_number
     *
     * @mbg.generated Sun Mar 07 22:26:42 CST 2021
     */
    int updateByPrimaryKey(SerialNumber record);
}